name: WY's Code Book
url: http://wycodebook.github.io/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

timezone: America/Los_Angeles

excerpt_separator: "<!-- more -->"

collections:
  resource:
    output: true
    permalink: /resource/:title
