name: Curious-Yu
url: https://Curious-Yu.github.io/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

timezone: America/Los_Angeles

excerpt_separator: "<!-- more -->"

collections:

  posts:
    output: true
    permalink: /posts/:title/

incremental: true