name: Curious-Yu
url: https://Curious-Yu.github.io/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

timezone: America/Los_Angeles

excerpt_separator: "<!-- more -->"

permalink: /:categories/:year/:month/:day/:title:output_ext

collections:

  problems:
    output: true
    permalink: /problems/:title/
    title: Solved Problems

  projects:
    output: true
    permalink: /projects/:title/
    title: Projects
