name: Curious-Yu
url: https://Curious-Yu.github.io/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

timezone: America/Los_Angeles

excerpt_separator: "<!-- more -->"

collections:
  resources:
    output: true
    permalink: /resources/:path/

  problems:
    output: true
    permalink: /problems/:path/

  projects:
    output: true
    permalink: /projects/:path/
